name: markdown2pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: convert md to pdf
        uses: docker://pandoc/latex:3.5
        with:	
          entrypoint: /bin/sh
          args: -c "for f in *.md; do pandoc $f -s -o ${f%.md}.pdf; done"
      - uses: actions/upload-artifact@v4
        with:
          name: assets
          path: assets
      - name: Commit files # transfer the new pdf files back into the repository
        run: |
          git config --local user.name "Kevin-Mattheus-Moerman"
          git add .
          git commit -m "Updating pdfs"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true


